### PR TITLE
Add high level process types

### PR DESCRIPTION
**Pull request by bkolobara**
As you can probably tell from the line `3,782 additions and 1,386 deletions`, this is somewhat of a big change to lunatic's rust library. This branch is still WIP and what I'm looking here most for is feedback on the general direction.

This work was inspired by this issue: https://github.com/lunatic-solutions/rust-lib/issues/10. I tried to keep things as backwards compatible as possible, but this PR does some fundamental changes to existing processes and adds much more functionality (serialization, protocols, supervisors, ...).

The lunatic vm brings some of the popular ideas from Erlang to all programming languages that compile to wasm. Over the last two years I have spent a lot of time trying to fit some of Erlang's patterns into the Rust type system. This PR is the next step in this process. Let's get started and break all the new changes down.

## Serialization formats

Processes in lunatic don't share any memory and if they are exchanging some data with each other they do it through messages. A message is just an `u8` buffer and if we are sending higher level structs between processes we need to serialize them first. Until now this library had a hardcoded serializer built in (`MsgPack`) that was used for all messages. This PR allows us to switch out the default serializer through a type hint:

```rust
// Use the default serializer (Bincode)
let proc = spawn::<Process<TypeX>, _>((), |_, mailbox| {}).unwrap();
// Use the protocol buffers serializer
use lunatic::serializer::ProtocolBuffers;
let proc = spawn::<Process<TypeX, ProtocolBuffers>, _>((), |_, mailbox| {}).unwrap();
```

In the second example all messages (of type `TypeX`) are going to be serialized with the protocol buffers serializer. And the `mailbox` is automatically going to deserialize them using the same deserializer type. All this information is encoded in the type system and checked during compile time.

We provide a few common serializers (`Bincode`, `MsgPack`, `Json` & `ProtocolBuffers`), but you can easily add your own by implementing the trait `lunatic::serializer::Serializer`.

## Regular processes

As we can see from the previous example, not much has changed with the existing `Process` type. It's still spawned from a function that can capture some environment and that gets a mailbox to handle messages sent to the process.

### `spawn` function

The `spawn` and `spawn_link` functions were extended to be able to spawn different process types and need to get a type hint through a generic.

## The `Task`

A `Task` is a new one-off process that does some computation asynchronously and returns a value.

```rust
let task = spawn::<Task<()>, _>((), |_| println!("Hi from a task!")).unwrap();
task.result(); // Wait on task to finish
```

Through the `result` method you get back the return value of the task. Even if the result value is `()` the calling process will block on the `task.result()` call until the task finishes.

## The `BackgroundTask`

If you don't want to wait on the task you can spawn a `BackgroundTask`:

```rust
spawn::<BackgroundTask, _>((), |_| println!("Don't wait on me!")).unwrap();
```

Both `Task` and `BackgroundTask` can use a custom serializer:

```rust
use lunatic::serializer::MessagePack.
spawn::<BackgroundTask<MessagePack>, _>((), |_| println!("Don't wait on me!")).unwrap();
```

## The `Server`

Another new addition to processes in lunatic is the `Server`. The server is spawned from a function and an initial state. On every message received the function is invoked, the state can be changed and a response can be sent back:

```rust
let child = spawn::<Server<i32, i32>, _>(0, |state, message| {
    *state += message;
    *state
}) .unwrap();

assert_eq!(child.request(1), 1);
assert_eq!(child.request(2), 3);
assert_eq!(child.request(3), 6);
```

Requests can be sent to the server through the `request` method.

## The `GenericServer`

The `GenericServer` is similar to the `Server` process, but allows you to express behaviour for different message types (generic types?). It's closest to the one proposed in the issue: https://github.com/lunatic-solutions/rust-lib/issues/10. It's probably easier to get a feeling for it through an example:

```rust
// Server state.
#[derive(serde::Serialize, serde::Deserialize)]
struct TestServer(i32);

// Increment message
#[derive(serde::Serialize, serde::Deserialize)]
struct Inc(i32);

// Count request
#[derive(serde::Serialize, serde::Deserialize)]
struct Count;

impl HandleMessage<Inc> for TestServer {
    fn handle(&mut self, message: Inc) {
        self.0 += message.0;
    }
}

impl HandleRequest<Count> for TestServer {
    type Result = i32;

    fn handle(&mut self, _: Count) -> Self::Result {
        self.0
    }
}

main() {
    let server = spawn::<GenericServer<_>, _>(TestServer(0), |_state| {}).unwrap();
    server.send(Inc(33));
    server.send(Inc(55));
    let result = server.request(Count);
    assert_eq!(result, 88);
}
```

The `GenericServer` is also characterised through a state (`struct TestServer(i32)`). This state can be mutated by defining message and request handlers for different types. A message can be sent to the server using the `send` method, and this call will not block. A `request` expects a return value to be sent back and will block until the return value is received. Everything is type checked during compile type. A `send` method can't be called on a type if no `HandleMessage` is implemented for this particular type for the `TestServer`.

## The `Protocol`

A `Protocol` is an (experimental) process that allows you to use session types in rust to define protocols between processes. A protocol is a series of messages that are exchanged, and lets us express behaviour such as the following: Process `a` will receive two messages of type `i32`, add them together and send back a response also of type `i32`. To define this protocol we just need to define a new type:

```rust
type AddProtocol = Recv<i32, Recv<i32, Send<i32, End>>>;
```

Now we can spawn a protocol using this type:

```rust
let a =
    spawn::<Protocol<<AddProtocol as HasDual>::Dual>, _>(1, |capture: i32, protocol| {
        assert_eq!(capture, 1);
        let (protocol, a) = protocol.receive();
        let (protocol, b) = protocol.receive();
        let _ = protocol.send(capture + a + b);
    })
    .unwrap();
assert_eq!(child.tag.id(), 130);
let a = child.send(2);
let a = child.send(2);
let (_, result) = child.receive();
assert_eq!(re
```

Rust can automatically generate for us a `Dual` type for process `a`. The `Dual` type defines the opposite behaviour, e.g. if one process is sending a message of type `T`, the other one is going to be receiving a message of type `T`. We can leverage here rust's type system to force us to use the correct order of `send` and `receive` calls. If we didn't follow the order expressed with the `AddProtocol` type, this code wouldn't even compile. `Send` and `Receive` are just some of the types that can be used to define a protocol. We also have `Choice` & `Offer` for branching. Later we could introduce recursive protocols, etc. It just depends how much complexity we want to push onto the type system. For now I think we cover the most common use cases.

If a `Protocol` is dropped before it reaches the `End` state, the process will panic. This can be used together with `spawn_link` to avoid dead-locks during runtime. This is a property that can't be checked during compile time.

## The Supervisor

The `Supervisor` is a process who's only goal is to supervise other processes and re-spawn them if they die. The idea of a supervisor is taken from [Erlang](https://www.erlang.org/doc/man/supervisor.html). Similar to `Protocols`, the `Supervisors` are highly experimental and will probably need a few iterations until we find the right ergonomics. Here is a demonstration of how it currently works:

```rust
#[derive(serde::Serialize, serde::Deserialize, Default)]
struct TestSupervisor {
    child: Option<Supervised<Server<i32, i32>>>,
}

impl Supervise for TestSupervisor {
    fn init(&mut self, children: &mut Children) {
        // Supervise a server
        let supervised = children.supervise::<Server<i32, i32>, _>(0, |state, message| {
            *state += message;
            // If we reach a state of 3 fail after answering request
            if *state == 3 {
                spawn_link::<BackgroundTask, _>((), |_| panic!("kill parent")).unwrap();
            }
            *state
        });
        // Store a reference to the child
        self.child = Some(supervised);
    }
}

impl HandleSupervisorRequest<i32> for TestSupervisor {
    type Result = i32;

    fn handle(&mut self, req: i32, children: &mut Children) -> Self::Result {
        // Just forward the request to the supervised server.
        let proc = self.child.as_mut().unwrap().process(children).unwrap();
        proc.request(req)
    }
}

fn main() {
    let supervisor = spawn::<Supervisor<_>, _>(TestSupervisor::default(), |_state| {}).unwrap();

    assert_eq!(supervisor.request(1), 1);
    assert_eq!(supervisor.request(1), 2);
    assert_eq!(supervisor.request(1), 3);
    // Child server dies at this point.
    // New child starts from fresh state
    sleep(Duration::from_millis(100));
    assert_eq!(supervisor.request(1), 1);
    assert_eq!(supervisor.request(1), 2);
    assert_eq!(supervisor.request(1), 3);
}
```

The supervisor is the magic that allows developers to build truly fault tolerant apps in Erlang. Because of Erlang's dynamic properties it's hard to have a 1 on 1 translation of the supervisor to Rust's strong type system. We still need to figure out how to incorporate some of the ideas into Rust's type system and how to compose supervision trees and manage them.

## Miscellaneous

Some other changes:

### `register_type` & `lookup_type`

It's a type safe implementation of the existing `register` & `lookup` functions (now called `register_name` & `lookup_name`). If the looked up process doesn't match the type of the expected one, it returns a value of `None`.

### `ThisModule` is now implicitly added to an environment

The `Environment` type now directly expose the functions `spawn` and `spawn_link` that can be used to spawn processes into it. On the first use the currently running module is added to the environment.

### `spawn!` & `spawn_link!` macros

The `spawn` function got a bit more complicated as it now needs to deal with a variety of different process types. Rust is smart when it comes to type inference, but there is still a lot of boilerplate and `_` usage on generics. To simplify working with `spawn` there is now a new macro that analyses the content and adds the right boilerplate for each process type:

```rust
// Spawn a background process
spawn!(@background || println!("Hello from the background!"));
// Spawn a task that captures a the `local` variable
let task = spawn!(@task |local| format!("Hello task! {}", local));
```

## Feedback wanted!

Until now the only way to send different types of messages to a process was by wrapping them into an `enum` and checking on the receiving side what type is received. It was also impossible to guarantee during compile time that a particular process is sending something back (the message could just be ignored, even with the `Request` type we had previously). The introduction of these new process types changes this, it gives us much more feedback during compile time.

At the same time there are other additions that I think would be useful. I wanted to add them to this PR too, to get a feeling on how everything works and composes together.

This PR is still in a volatile state and things may change. I would love to get some feedback at this stage though. Many of these ideas are subjective and a result of me exploring "Erlang in Rust" over the last two years.

### CODE REVIEW

**Comment by sleipnir** [comment]
I really liked what I saw here. Congratulations on the hard work.
I felt a certain difficulty with the Supervisor, I think just a little bit can keep a little bit, for me the Supervised Supervisor code, and I think it would make it difficult to create separate from more complex hierarchical relationships as we do nothing Erlang/Elixir with the trees supervision.
I really liked the spawn macro

**Review by sleipnir — COMMENTED** [review]
why was gen_server removed?

**Comment by bkolobara** [comment]
> why was gen_server removed?

The Server was removed and GenericServer was renamed to Server.

**Comment by sleipnir** [comment]
> > why was gen_server removed?
> 
> The Server was removed and GenericServer was renamed to Server.

I think GenServer is an abstraction about managing the state of a Process. Since a GenServer doesn't erlang expose a client-server API to interact with the state of the Process, and as this was very common at the time erlang was created, they named it GenServer. I always thought that name was awful, and I also think Server is an awful name for what he does. Because in reality a GenServer is much more a way of interacting with the state of a Process through an API than on client and servers.
I think ProcessState or ActorState, AbstractActor (Akka uses this one) or something like that reflects much more the intent of what this type of entity is about than Server or GenServer. And since the intention is to move away from erlang terminology, I think it would be better to try to define the name of the real thing.

Wdyt?

**Comment by bkolobara** [comment]
I'm trying different approaches to see what "feels right" in real world code examples, but nothing so far felt perfect. I was thinking to just go with `GenServer` because of the familiarity, but I also like your suggestion `ProcessState`.

It's a trait you implement for the **state of a process**. And then you launch the process with `State::start()`. I also would like to move the terminology to state management, instead of client/server. Thanks for the suggestion @sleipnir.

**Comment by sleipnir** [comment]
> I'm trying different approaches to see what "feels right" in real world code examples, but nothing so far felt perfect. I was thinking to just go with `GenServer` because of the familiarity, but I also like your suggestion `ProcessState`.
> 
> It's a trait you implement for the **state of a process**. And then you launch the process with `State::start()`. I also would like to move the terminology to state management, instead of client/server. Thanks for the suggestion @sleipnir.
> 
> EDIT: `AbstractProcess` could also be a good candidate.

I like both (AbstractProcess is perhaps most familiar to most programming models, although ProcessState is a better reflection of what it actually does)

**Pull request merged**
